development:
  adapter: postgresql
  database: albums_development
  host: 127.0.0.1

test:
  adapter: postgresql
  database: albums_test
  host: 127.0.0.1

production:
  adapter: postgresql
  database: albums_production
